# This rule is not used by the project runtime-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the infini.cloud.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: runtime-operator
    app.kubernetes.io/managed-by: kustomize
  name: app-applicationdefinition-editor-role
rules:
- apiGroups:
  - infini.cloud
  resources:
  - applicationdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infini.cloud
  resources:
  - applicationdefinitions/status
  verbs:
  - get
