apiVersion: app.infini.cloud/v1
kind: ApplicationDefinition
metadata:
  name: my-infini-console # 应用实例名称
  namespace: default # 替换为你的命名空间
spec:
  components:
    - name: infini-console # 组件实例名称 (会影响资源名称)
      # type: operator # 引用上面的 ComponentDefinition
      properties:
        # --- 核心配置 ---
        replicas: 1 # 副本数 (例如: 1 或 3)
        image:
          repository: docker.1ms.run/infinilabs/console # 目标镜像
          tag: 1.29.4-2108
        command:
          - sh
          - -c
          - |
            if [ ! -e /config_bak/certs ]; then
              cp -rf /config/* /config_bak
            fi
            exec /console
        ports:
          - name: http-9000 # 主要应用端口
            containerPort: 9000
            protocol: TCP
          # - name: metrics # 如果有其他端口
          #   containerPort: 9090
        storage: # StatefulSet 通常需要存储. 目前删除 Pod 不会删除 PVC，todo
          enabled: true
          size: 2Gi # <-- 按需调整存储大小
          mountPath: /data # <-- !!! 确认 infinilabs/gateway 数据/配置挂载路径 !!!
          volumeClaimTemplateName: data # VCT 名称 (通常与 mountPath 相关)
          accessModes:
            - ReadWriteOnce
          storageClassName: local # <--- !!! 替换为你集群中有效的 StorageClass !!!
#        serviceAccount:  # ServiceAccount 名称
#            create: false # 是否创建 ServiceAccount, 默认值为 false
#            name: controller-manager # <-- !!! 确认 ServiceAccount 名称 !!!
        # --- 可选配置 ---
        service: # 服务暴露配置
          type: NodePort # 使用 NodePort 便于测试，或 LoadBalancer
          ports:
            - name: http-9000 # Service 端口名称
              containerPort: 9000 # Service 监听的端口
               # targetPort: 8080 # 转发的目标 Pod 端口 (默认等于 containerPort)
               # nodePort: 30080 # 可选：指定 NodePort 端口
        resources:
          requests:
            cpu: "0.5" # 500m
            memory: "512Mi"
          limits:
            cpu: "1" # 1 Core
            memory: "1Gi"
        probes: # <-- 强烈建议根据实际情况配置健康检查
          liveness:
            httpGet:
              path: /_info # <-- !!! 确认健康检查路径 !!!
              port: 9000        # <-- !!! 确认健康检查端口 !!!
            initialDelaySeconds: 15 # 给予较长启动时间
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readiness:
            httpGet:
              path: /_info # <-- !!! 确认就绪检查路径 !!!
              port: 9000       # <-- !!! 确认就绪检查端口 !!!
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
        env:
          - name: INFINI_CONSOLE_ENDPOINT
            value: http://console:9000/
        configMounts: # 需要配合 configFiles 告诉 Builder 如何挂载
          - name: infini-console-config # 指向上面生成的 ConfigMap
            mountPath: /config # 挂载配置文件的目录
            readOnly: true
        configFiles: # 配置文件内容. configmap 有更新会自动重启gw
          "security.yml": |
            security:
              enabled: true
              oauth:
                authorize_url: https://github.com/login/oauth/authorize
                client_id: your_github_acess_client_id
                client_secret: your_github_acess_client_secret
                default_roles:
                - ReadonlyUI
                - DATA
                enabled: true
                redirect_url: http://your_console_endpoint/sso/callback/
                role_mapping:
                  luohoufu:
                  - Administrator
                  medcl:
                  - Administrator
                scopes: []
                token_url: https://github.com/login/oauth/access_token